weights: yolov5s.pt
cfg: ""
data: "SeaDroneSee.yaml"
hyp: 'data/hyps/hyp.scratch-low.yaml'
save_dir: null
epochs: 30
batch_size: 16
imgsz: 640
rect: false
resume: false
nosave: false
noval: false
noautoanchor: false
evolve: null # ??? probably should put 300 
bucket: ""
cache: ram # ??? probably should put "ram"
image_weights: false
device: ""
multi_scale: false
single_cls: false
optimizer: "SGD"
sync_bn: false
workers: 8
project: "runs/train"
name: "exp"
exist_ok: false
quad: false
cos_lr: false
label_smoothing: 0
patience: 100
freeze: 
  0: 0 # todo
save_period: -1
local_rank: -1
entity: cyr1ll
upload_dataset: false
bbox_interval: -1
artifact_alias: latest
run_name: "baseline"
debug: false